/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intefazYBackend;

import analizadores.AnalizadorLexico;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.TransicionLexica;
import modelos.TransicionSintactica;

/**
 *
 * @author Luis Monterroso
 */
public class MenuPrincipal extends javax.swing.JInternalFrame {

    private BackendMenuPrincipal backend;
    private AnalizadorLexico analizador;

    private ArrayList<TransicionLexica> tablaDeTransicionesLexicas;
    private ArrayList<String> palabrasReservadas;
    private ArrayList<TransicionSintactica> tablaDeTrasicionesSintacticas;

    public MenuPrincipal(ArrayList<TransicionLexica> tablaDeTransicionesLexicas, ArrayList<String> palabrasReservadas, ArrayList<TransicionSintactica> tablaDeTrasicionesSintacticas) {
        this.tablaDeTransicionesLexicas = tablaDeTransicionesLexicas;
        this.palabrasReservadas = palabrasReservadas;
        this.tablaDeTrasicionesSintacticas = tablaDeTrasicionesSintacticas;
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);//con esto le quitamos la barra de arriba
        backend = new BackendMenuPrincipal();
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenedor = new javax.swing.JTextArea();
        btnAbrirProyecto = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnGuardarComo = new javax.swing.JButton();
        btnNuevoProyecto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCopiar = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        btnPegar = new javax.swing.JButton();
        btnRehacer = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        labelColumna = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelFila = new javax.swing.JLabel();
        btnPegar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(104, 33, 122));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1666, 668));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 40, 43));

        txtContenedor.setColumns(20);
        txtContenedor.setRows(5);
        txtContenedor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtContenedorCaretUpdate(evt);
            }
        });
        txtContenedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContenedorKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtContenedor);

        btnAbrirProyecto.setBackground(new java.awt.Color(104, 33, 122));
        btnAbrirProyecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAbrirProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrirProyecto.setText("Abrir archivo");
        btnAbrirProyecto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAbrirProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrirProyecto.setFocusable(false);
        btnAbrirProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirProyectoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(104, 33, 122));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar archivo");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusable(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnGuardarComo.setBackground(new java.awt.Color(104, 33, 122));
        btnGuardarComo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardarComo.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarComo.setText("Guardar como");
        btnGuardarComo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnGuardarComo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarComo.setFocusable(false);
        btnGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarComoActionPerformed(evt);
            }
        });

        btnNuevoProyecto.setBackground(new java.awt.Color(104, 33, 122));
        btnNuevoProyecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevoProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProyecto.setText("Nuevo proyecto");
        btnNuevoProyecto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnNuevoProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoProyecto.setFocusable(false);
        btnNuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProyectoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(37, 37, 38));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaTokens);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 550, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reporte de tokens");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnCopiar.setBackground(new java.awt.Color(104, 33, 122));
        btnCopiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCopiar.setForeground(new java.awt.Color(255, 255, 255));
        btnCopiar.setText("Copiar");
        btnCopiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCopiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCopiar.setFocusable(false);
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        btnDeshacer.setBackground(new java.awt.Color(104, 33, 122));
        btnDeshacer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeshacer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshacer.setText("Deshacer");
        btnDeshacer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDeshacer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeshacer.setFocusable(false);
        btnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerActionPerformed(evt);
            }
        });

        btnPegar.setBackground(new java.awt.Color(104, 33, 122));
        btnPegar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPegar.setForeground(new java.awt.Color(255, 255, 255));
        btnPegar.setText("Pegar");
        btnPegar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnPegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPegar.setFocusable(false);
        btnPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarActionPerformed(evt);
            }
        });

        btnRehacer.setBackground(new java.awt.Color(104, 33, 122));
        btnRehacer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRehacer.setForeground(new java.awt.Color(255, 255, 255));
        btnRehacer.setText("Rehacer");
        btnRehacer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnRehacer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRehacer.setFocusable(false);
        btnRehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRehacerActionPerformed(evt);
            }
        });

        btnEjecutar.setBackground(new java.awt.Color(104, 33, 122));
        btnEjecutar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEjecutar.setForeground(new java.awt.Color(255, 255, 255));
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEjecutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEjecutar.setFocusable(false);
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDeshacer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRehacer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCopiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoProyecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btnAbrirProyecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarComo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPegar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAbrirProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarComo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPegar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRehacer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeshacer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1670, 590));

        labelColumna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelColumna.setForeground(new java.awt.Color(255, 255, 255));
        labelColumna.setText("0");
        getContentPane().add(labelColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fila");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Columna");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, -1, -1));

        labelFila.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFila.setForeground(new java.awt.Color(255, 255, 255));
        labelFila.setText("1");
        getContentPane().add(labelFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, -1, -1));

        btnPegar1.setBackground(new java.awt.Color(104, 33, 122));
        btnPegar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPegar1.setForeground(new java.awt.Color(255, 255, 255));
        btnPegar1.setText("Acerca de...");
        btnPegar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnPegar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPegar1.setFocusable(false);
        btnPegar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 610, 131, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        txtContenedor.copy();
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarActionPerformed
        txtContenedor.paste();
        backend.apilarUndo(txtContenedor);

    }//GEN-LAST:event_btnPegarActionPerformed

    private void btnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerActionPerformed
        backend.undo(txtContenedor);
    }//GEN-LAST:event_btnDeshacerActionPerformed

    private void btnRehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRehacerActionPerformed
        backend.redo(txtContenedor);
    }//GEN-LAST:event_btnRehacerActionPerformed

    private void txtContenedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContenedorKeyReleased
        backend.apilarUndo(evt, txtContenedor);
    }//GEN-LAST:event_txtContenedorKeyReleased

    private void btnAbrirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirProyectoActionPerformed
        backend.seleccionarArchivo(txtContenedor);
    }//GEN-LAST:event_btnAbrirProyectoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        backend.guardarArchivo(txtContenedor, "txt");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnPegar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegar1ActionPerformed
        JOptionPane.showMessageDialog(this, "Alumno: Luis Antonio Monterroso Guzman\nCarnet: 202031794", "Creador", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnPegar1ActionPerformed

    private void btnNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProyectoActionPerformed
        backend.nuevoProyecto(txtContenedor);
    }//GEN-LAST:event_btnNuevoProyectoActionPerformed

    private void btnGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarComoActionPerformed
        backend.guardarArchivo(txtContenedor, "html");
        backend.guardarArchivo(txtContenedor, "txt");
    }//GEN-LAST:event_btnGuardarComoActionPerformed

    private void txtContenedorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtContenedorCaretUpdate
        backend.contarFilasYColumnas(labelFila, labelColumna, evt);
    }//GEN-LAST:event_txtContenedorCaretUpdate

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        analizador = new AnalizadorLexico(tablaTokens, txtContenedor.getText(), tablaDeTransicionesLexicas, palabrasReservadas, tablaDeTrasicionesSintacticas);
        analizador.analizar();
    }//GEN-LAST:event_btnEjecutarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirProyecto;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarComo;
    private javax.swing.JButton btnNuevoProyecto;
    private javax.swing.JButton btnPegar;
    private javax.swing.JButton btnPegar1;
    private javax.swing.JButton btnRehacer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelColumna;
    private javax.swing.JLabel labelFila;
    private javax.swing.JTable tablaTokens;
    private javax.swing.JTextArea txtContenedor;
    // End of variables declaration//GEN-END:variables
}
